//WidgetPage Elements
export const elements = {
    autoCompleteContainer: '#autoCompleteMultipleContainer > .auto-complete__control > .auto-complete__value-container',
    autoCompleteMenu: '.auto-complete__menu',
    autoCompleteLabel: '.auto-complete__multi-value__label',
    datePikerInput: '#datePickerMonthYearInput',
    datePikerChosen: '.react-datepicker__current-month',
    dateAndTimePickerInput: '#dateAndTimePickerInput',
    selectedDateNtime: '.react-datepicker__time-list-item--selected',
    sectionOneContent: '#section1Content > p',
    sectionTwoContent: '#section2Content > :nth-child(1)',
    sectionThreeContent: '#section3Content > p',
    tabButton: '#tabButton',
    openStub: '@openStub',
    alertButton: '#alertButton',
    timerAlertButton: '#timerAlertButton',
    confirmButton: '#submit',
    promtButton: '#promtButton',
    promptResult: '#promptResult',
    userName: '#userName',
    userEmail: '#userEmail',
    currentAddress: '#currentAddress',
    permanentAddress: '#permanentAddress',
    submitButton: '#submit',
    nameContainer: '#name',
    actionElement: '#item-1',
    checkBoxContainer: '.text-center',
    checkBox: '.rct-title',
    successMessage: '.text-success',
    addNewRecordButton: '#addNewRecordButton',
    doubleClickMessage: '#doubleClickMessage',
    rightClickMessage: '#rightClickMessage',
    dynamicClickMessage: '#dynamicClickMessage',
    groupOfDrugNDrop: '.list-group-item',
    gridButton: '#demo-tab-grid',
    cubeInteractiveElement: '#demo-tabpane-grid',
    listOfItems: '.list-group-item',
    resizableHandle: '.react-resizable-handle',
    resizableBox: '#resizableBoxWithRestriction',
    showSmallModal: '#showSmallModal',
    modalContent: '.modal-content',
    modalBody: '.modal-body',
    closeSmallModal: '#closeSmallModal',
    showLargeModal: '#showLargeModal',
    closeLargeModal: '#closeLargeModal'
}
